### ISSUE TITLE
HasMessages does not work with attributes

### ISSUE THREAD

**Issue by Mailaender** [Ygg01/Linguini#25]
You can only check by removing attributes first:

```csharp
var attributes = key.LastIndexOf('.');
if (attributes > 0)
	return bundle.HasMessage(key.Remove(attributes));
else
	return bundle.HasMessage(key);
```

**Comment by Ygg01** [comment]
Valid point, but it's kinda of a breaking change.

You ok with another method or some default argument overload?

**Comment by Mailaender** [comment]
We use it for CI checks if the message is missing in `.ftl` or unused.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/20400/files#diff-75c06187d0ff58a1c3b14c429a8ad83030ec38fc0c6b4e3b6eb9b9bdce35cabfR122
