### ISSUE TITLE
Dropping support for Net4.6 and Net5

### ISSUE THREAD

**Issue by Ygg01** [Ygg01/Linguini#32]
GitHub CI is complaining about no support for Net5.0, and Net 4.6 tests are already causing problems in the pipeline. 

@Mailaender Does that affect you? I know SS14 is on at least Net7.

**Comment by Mailaender** [comment]
@OpenRA is at .NET 6 and older versions never shipped Linguini.

**Comment by Ygg01** [comment]
Ok, then that was someone else. Thanks for feedback.

**Comment by Ygg01** [comment]
@mtkennerly what version of dotnet are you?

**Comment by mtkennerly** [comment]
I'm limited to .NET Framework 4.6.2 since that's what Playnite currently requires for plugins, but I can stay on the current/older version of Linguini until Playnite updates (https://github.com/JosefNemec/Playnite/issues/1141), so it's not a problem :)

**Comment by Ygg01** [comment]
> I'm limited to .NET Framework 4.6.2 since that's what Playnite currently requires for plugins, but I can stay on the current/older version of Linguini until Playnite updates ([JosefNemec/Playnite#1141](https://github.com/JosefNemec/Playnite/issues/1141)), so it's not a problem :)

I'm 70% sure it will work on win/linux (I tested it locally on win), but not sure about MacOS (it's complicated there). I'll bump major version just to be sure.
