### ISSUE TITLE
Attributes are not parsed if they begin with a tab character

### ISSUE THREAD

**Issue by eXplowar** [Ygg01/Linguini#53]
Ffl-file with tabs for attributes:

![2024-01-19_224956](https://github.com/Ygg01/Linguini/assets/3119119/ae71c514-a388-4447-a562-d153bea83937)

Result of parsing (**Linguini incorrectly identifies this as Junk**):

![2024-01-19_224910](https://github.com/Ygg01/Linguini/assets/3119119/fbb3aa29-6779-492d-bfb6-0cc217f50c5b)

Ftl without tabs (**no errors, attributes were defined correctly**):

![2024-01-19_225124](https://github.com/Ygg01/Linguini/assets/3119119/7ffba635-843a-4603-8ff6-7dff2ea696ef)

Result of parsing:

![2024-01-19_225346](https://github.com/Ygg01/Linguini/assets/3119119/851c4d44-52af-43e0-9d54-29c5a97f7ed9)

Not sure if this will be correct, but my suggestion is to adjust the condition on line 400:
`if (_reader.TryPeekChar(out var c) && c.IsAsciiAlphabetic() || c == '\u0009')`

![2024-01-19_232659](https://github.com/Ygg01/Linguini/assets/3119119/07f892f2-f7e2-4956-b944-509749f02c93)

**Comment by Ygg01** [comment]
> Result of parsing (**Linguini incorrectly identifies this as Junk**):

Small but important distinction. Linguini **correctly** identifies this as junk. 

Look at https://github.com/projectfluent/fluent/issues/165

Tab was removed as valid indentation.

Further proof is the Fluent spec:
https://github.com/projectfluent/fluent/blob/feffc720fa5d5621a703f42731d709e216fc6730/spec/fluent.ebnf#L32
```ebnf
Attribute             ::= line_end blank? "." Identifier blank_inline? 

/* Whitespace */
blank_inline        ::= "\u0020"+
line_end            ::= "\u000D\u000A"
                      | "\u000A"
                      | EOF
blank               ::= (blank_inline | line_end)+
```
So an attribute is a rule that says `\n` then `OneOrMore('\n' or ' ')` then `.` then identifier.

**Comment by eXplowar** [comment]
Thanks for the answer, we'll know ;)

**Comment by Ygg01** [comment]
> Thanks for the answer, we'll know ;)

What you can do is fix files to use spaces or fork Linguini.Syntax for your own usage. But then not sure how that would work with Nuget.
